### ISSUE TITLE
Icon for .yamllint not loaded on startup

### ISSUE THREAD

**Issue by Adrylen** [prazdevs/zarp-icons#1]
I use a `.yamllint` file for my project, and I saw there's no icon available on startup.

![image](https://user-images.githubusercontent.com/16221546/188450492-7e0f3fef-5018-4b6d-b512-371a1e718086.png)

But when I opened the file, VSCode managed to highlight it as a `yaml` file and the icon was loaded after.

![image](https://user-images.githubusercontent.com/16221546/188450587-eab73fef-1f58-432f-82ac-b9ebdc5b2357.png)

Any way to fix it ?

**Comment by prazdevs** [comment]
fixed in c8c3fb0 🎉
