### ISSUE TITLE
Add option to hide folder arrows

### ISSUE THREAD

**Issue by rabrenio** [prazdevs/zarp-icons#6]
It would be nice if we can add the option the hide the arrow besides the folder icon. Some icon theme offers a solution to handle this. tia

<img width="41" alt="Screenshot 2024-02-26 at 12 20 37 PM" src="https://github.com/prazdevs/zarp-icons/assets/11053576/156ce1a2-1733-444f-b7e2-985dbde11ae6">

**Comment by prazdevs** [comment]
Hi :) I don't really maintain this extension/theme anymore as I ported it (and much more) to https://github.com/catppuccin/vscode-icons

It's the same design with a more elegant and consistent color palette, and it offers customization such as hiding the folder arrows as you request :)

Here is the marketplace link https://marketplace.visualstudio.com/items?itemName=Catppuccin.catppuccin-vsc-icons

**Comment by rabrenio** [comment]
@prazdevs thank you for this.
